disabled = false
languageCode = "zh-CN"
languageName = "Simplified Chinese"
weight = 1

[params]
  displayName = "简体中文"
  isoCode = "zh-CN"
  rtl = false

 [params.author]
   headline = "全栈工程师 & 旅行者"
   bio = "梦里不知身是客，一晌贪欢"