disabled = false
languageCode = "en"
languageName = "English"
weight = 1

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false

 [params.author]
   headline = "Full Stack Engineer & Traveler"
   bio = "In dreams, unaware that I am a guest, I indulge in fleeting joy"