[[main]]
  name = "关于"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "项目"
  pageRef = "projects"
  weight = 30

 [[footer]]
   name = "标签"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "分类"
   pageRef = "categories"
   weight = 20
